# Generated by Django 5.2.4 on 2025-07-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_parsed_text', models.TextField(blank=True, help_text='The parsed text of the resume reviewed.', null=True)),
                ('resume_file', models.FileField(help_text='The original resume file uploaded by the user.', upload_to='resumes/')),
                ('overall_score', models.FloatField(blank=True, default=0.0, help_text='Overall score of the resume review.', null=True)),
                ('overall_feedback', models.TextField(blank=True, help_text='Overall feedback provided by the reviewer.', null=True)),
                ('resume_stats', models.TextField(blank=True, help_text='Statistics of the resume review.', null=True)),
                ('sections_found', models.TextField(blank=True, help_text='Sections found in the resume.', null=True)),
                ('missing_sections', models.TextField(blank=True, help_text='Sections that are missing in the resume.', null=True)),
                ('issues_found', models.TextField(blank=True, help_text='Issues found in the resume.', null=True)),
                ('keyword_match_score', models.FloatField(blank=True, default=0.0, help_text='Score based on keyword matching in the resume.', null=True)),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improving the resume.', null=True)),
            ],
        ),
    ]
